function Im_KD8071
global inter Images Centrs_metki CentrsEnd_strl n...
    dopusk Goden Datchik NameUnitDatcik  NumShkal...
    ImLed Otklonenie OtklonenieLedSum Color_Menu

% Datchik=char('УРОВЕНЬ ТОПЛИВА',...
%              'ТЕМПЕРАТУРА ОЖ',...
%              'ДАВЛЕНИЕ МАСЛА В ДВИГАТЕЛЕ',...
%              'ДАВЛЕНИЕ ВОЗДУХА ',...
%              'ДАВЛЕНИЕ МАСЛА В КПП',...
%              'НАПРЯЖЕНИЕ');

% NameUnitDatcik=char('(проценты)',...
%                     '(градусы)',...
%                     '(x 100 кПа)',...
%                     '(x 100 кПа)',...
%                     '(x 100 кПа)',...
%                     '(Вольт)');

n=menu_KD8071('ВЫБОР УКАЗАТЕЛЯ ',Datchik(1,:), Datchik(2,:),Datchik(3,:),...
    Datchik(4,:),Datchik(5,:),Datchik(6,:),'Аварийные светодиоды');

switch n
    case 1
        NameFig=Datchik(1,:);
        NameUnit=NameUnitDatcik(1,:);
    case 2
        NameFig=Datchik(2,:);
        NameUnit=NameUnitDatcik(2,:);
    case 3
        NameFig=Datchik(3,:);
        NameUnit=NameUnitDatcik(3,:);
    case 4
        NameFig=Datchik(4,:);
        NameUnit=NameUnitDatcik(4,:);
              case 5
                  NameFig=Datchik(5,:);
                   NameUnit=NameUnitDatcik(5,:);
    case 6
        NameFig=Datchik(6,:);
        NameUnit=NameUnitDatcik(6,:);
    case 7
        NameFig='Аварийные светодиоды';
   otherwise     
        
end

if n==7
SCRsize=(get(0,'MonitorPosition'));
left=SCRsize(1);
bottom=SCRsize(2);
widht=SCRsize(3);
height=SCRsize(4)-19;

figure2 = figure...
    ('Color'           , [0.8 0.8 0.8],...
    'PaperPosition'   ,[0.25 2.5 8 6],...
    'NumberTitle'     ,'off', ...
    'Tag'             ,'figure2',...
    'Name'            ,'',...
    'PaperSize'       ,[20.98 29.68],...
    'PaperType'       ,'a4letter',...
    'Position'        , [left bottom widht height],...
    'Resize'          , 'off',...
    'Menu'            ,'none');




    set(figure2,'Name'            ,NameFig);
    axes1f2l = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes1f2l,'Position',[0.01 0.70 0.3 0.29]);
    axes1f2l;imshow(ImLed{1});hold on ;
    
    text0_10l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'bold',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.755 0.15 0.1] ,...
        'String'                ,Datchik(1,:),...
        'Visible'               ,'on');
    
    text0_110l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.725 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    %
    text0_111l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.705 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    
    
    
    
    if      (Otklonenie(1,5)==0)&&(OtklonenieLedSum(1)==1)
        set( text0_10l,'Foregroundcolor' ,'k');
        
    elseif  (Otklonenie(1,5)==0)&&(OtklonenieLedSum(1)>1)
        set( text0_10l,'Foregroundcolor' ,'r');
        set( text0_110l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(1));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_110l,'String' ,stroka);
        
    elseif  (Otklonenie(1,5)~=0)&&(OtklonenieLedSum(1)<=1)
        set( text0_10l,'Foregroundcolor' ,'r');
        set( text0_110l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(1));
        stroka=strcat('Не горит светодиод');
        set( text0_110l,'String' ,stroka);
        
    elseif  (Otklonenie(1,5)~=0)&&(OtklonenieLedSum(1)>1)
        set( text0_10l,'Foregroundcolor' ,'r');
        set( text0_110l,'Foregroundcolor' ,'r');
        set( text0_111l,'Foregroundcolor' ,'r');
        stroka=strcat('Не горит светодиод');
        set( text0_110l,'String' ,stroka);
        ch=int2str(OtklonenieLedSum(1));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_111l,'String' ,stroka);
        
    end
    %
    
    i=2;
    axes2f2l = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes2f2l,'Position',[0.01 0.40 0.3 0.29]);
    axes2f2l;imshow(ImLed{i});hold on ;
    
    text0_20l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'bold',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.505 0.15 0.1] ,...
        'String'                ,Datchik(i,:),...
        'Visible'               ,'on');
    
    text0_210l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.475 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    %
    text0_211l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.455 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    
    
    
    
    if  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)==1)
        set( text0_20l,'Foregroundcolor' ,'k');
        
    elseif  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)>1)
        set( text0_20l,'Foregroundcolor' ,'r');
        set( text0_210l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_210l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)<=1)
        set( text0_20l,'Foregroundcolor' ,'r');
        set( text0_210l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Не горит светодиод');
        set( text0_210l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)>1)
        set( text0_20l,'Foregroundcolor' ,'r');
        set( text0_210l,'Foregroundcolor' ,'r');
        set( text0_211l,'Foregroundcolor' ,'r');
        stroka=strcat('Не горит светодиод');
        set( text0_210l,'String' ,stroka);
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_211l,'String' ,stroka);
        
    end
    
    
    
    i=3;
    %
    axes3f2l = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes3f2l,'Position',[0.01 0.10 0.3 0.29]);
    axes3f2l;imshow(ImLed{3});hold on ;
    
    text0_30l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'bold',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.155 0.16 0.15] ,...
        'String'                ,Datchik(3,:),...
        'Visible'               ,'on');
    
    text0_310l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.14 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    %
    text0_311l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.308 0.12 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    
    
    
    
    if  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)==1)
        set( text0_30l,'Foregroundcolor' ,'k');
        
    elseif  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)>1)
        set( text0_30l,'Foregroundcolor' ,'r');
        set( text0_310l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_310l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)<=1)
        set( text0_30l,'Foregroundcolor' ,'r');
        set( text0_310l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Не горит светодиод');
        set( text0_310l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)>1)
        set( text0_30l,'Foregroundcolor' ,'r');
        set( text0_310l,'Foregroundcolor' ,'r');
        set( text0_311l,'Foregroundcolor' ,'r');
        stroka=strcat('Не горит светодиод');
        set( text0_310l,'String' ,stroka);
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_311l,'String' ,stroka);
        
    end
    
    
    i=4;
    axes4f2l = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes4f2l,'Position',[0.46 0.70 0.3 0.29]);
    axes4f2l;imshow(ImLed{i});hold on ;
    
    text0_40l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'bold',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.762 0.755 0.15 0.1] ,...
        'String'                ,Datchik(i,:),...
        'Visible'               ,'on');
    
    text0_410l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.762 0.725 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    %
    text0_411l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.762 0.705 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    %
    %
    %
    
    if      (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)==1)
        set( text0_40l,'Foregroundcolor' ,'k');
        
    elseif  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)>1)
        set( text0_40l,'Foregroundcolor' ,'r');
        set( text0_410l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_410l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)<=1)
        set( text0_40l,'Foregroundcolor' ,'r');
        set( text0_410l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Не горит светодиод');
        set( text0_410l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)>1)
        set( text0_40l,'Foregroundcolor' ,'r');
        set( text0_410l,'Foregroundcolor' ,'r');
        set( text0_411l,'Foregroundcolor' ,'r');
        stroka=strcat('Не горит светодиод');
        set( text0_410l,'String' ,stroka);
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_411l,'String' ,stroka);
        
    end
    %
    i=5;
    axes5f2l = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes5f2l,'Position',[0.46 0.40 0.3 0.29]);
    axes5f2l;imshow(ImLed{i});hold on ;
    
    text0_50l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'bold',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.762 0.505 0.15 0.1] ,...
        'String'                ,Datchik(i,:),...
        'Visible'               ,'on');
    
    text0_510l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.762 0.475 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    %
    text0_511l=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,10,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'left',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.762 0.455 0.15 0.1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    
    
    
    if  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)==1)
        set( text0_50l,'Foregroundcolor' ,'k');
        
    elseif  (Otklonenie(i,5)==0)&&(OtklonenieLedSum(i)>1)
        set( text0_50l,'Foregroundcolor' ,'r');
        set( text0_510l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_510l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)<=1)
        set( text0_50l,'Foregroundcolor' ,'r');
        set( text0_510l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Не горит светодиод');
        set( text0_510l,'String' ,stroka);
        
    elseif  (Otklonenie(i,5)~=0)&&(OtklonenieLedSum(i)>1)
        set( text0_50l,'Foregroundcolor' ,'r');
        set( text0_510l,'Foregroundcolor' ,'r');
        set( text0_511l,'Foregroundcolor' ,'r');
        stroka=strcat('Не горит светодиод');
        set( text0_510l,'String' ,stroka);
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_511l,'String' ,stroka);
        
    end
    
     i=6;
    %
     axes6f2l = axes('Parent',figure2);
     set(gca, 'Visible','on');
     set(axes6f2l,'Position',[0.46 0.10 0.3 0.29]);
     axes6f2l;imshow(ImLed{i});hold on ;
    
     text0_60l=uicontrol(figure2,...
      'Style'                 ,'text', ...
      'Foregroundcolor'       ,'k',...
      'Backgroundcolor'       ,[0.8 0.8 0.8],...
      'FontSize'              ,10,...
      'FontWeight'            ,'bold',...
      'FontName'              ,'Arial',...
      'HorizontalAlignment'   ,'left',...
      'Units'                 ,'normalized', ...
      'Position'              , [0.762 0.155 0.16 0.15] ,...
      'String'                ,Datchik(i,:),...
      'Visible'               ,'on');
    
     text0_610l=uicontrol(figure2,...
      'Style'                 ,'text', ...
      'Foregroundcolor'       ,'k',...
      'Backgroundcolor'       ,[0.8 0.8 0.8],...
      'FontSize'              ,10,...
      'FontWeight'            ,'normal',...
      'FontName'              ,'Arial',...
      'HorizontalAlignment'   ,'left',...
      'Units'                 ,'normalized', ...
      'Position'              , [0.762 0.14 0.15 0.1] ,...
      'String'                ,'',...
      'Visible'               ,'on');
    %
     text0_611l=uicontrol(figure2,...
      'Style'                 ,'text', ...
      'Foregroundcolor'       ,'k',...
      'Backgroundcolor'       ,[0.8 0.8 0.8],...
      'FontSize'              ,10,...
      'FontWeight'            ,'normal',...
      'FontName'              ,'Arial',...
      'HorizontalAlignment'   ,'left',...
      'Units'                 ,'normalized', ...
      'Position'              , [0.762 0.12 0.15 0.1] ,...
      'String'                ,'',...
      'Visible'               ,'on');
    
    
    
    
    if  (Otklonenie(i,5)==0)&(OtklonenieLedSum(i)==1)
        set( text0_60l,'Foregroundcolor' ,'k');
    
    elseif  (Otklonenie(i,5)==0)&(OtklonenieLedSum(i)>1)
        set( text0_60l,'Foregroundcolor' ,'r');
        set( text0_610l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_610l,'String' ,stroka);
    
    elseif  (Otklonenie(i,5)~=0)&(OtklonenieLedSum(i)<=1)
        set( text0_60l,'Foregroundcolor' ,'r');
        set( text0_610l,'Foregroundcolor' ,'r');
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Не горит светодиод');
        set( text0_610l,'String' ,stroka);
    
     elseif  (Otklonenie(i,5)~=0)&(OtklonenieLedSum(i)>1)
        set( text0_60l,'Foregroundcolor' ,'r');
        set( text0_610l,'Foregroundcolor' ,'r');
        set( text0_611l,'Foregroundcolor' ,'r');
        stroka=strcat('Не горит светодиод');
        set( text0_610l,'String' ,stroka);
        ch=int2str(OtklonenieLedSum(i));
        stroka=strcat('Горят ',' :',ch,' светодиода');
        set( text0_611l,'String' ,stroka);
    
     end
    
    
    
    
elseif n==1||n==2||n==3||n==4||n==5||n==6
    SCRsize=(get(0,'MonitorPosition'));
left=SCRsize(1);
bottom=SCRsize(2);
widht=SCRsize(3);
height=SCRsize(4)-19;

figure2 = figure...
    ('Color'           , [0.8 0.8 0.8],...
    'PaperPosition'   ,[0.25 2.5 8 6],...
    'NumberTitle'     ,'off', ...
    'Tag'             ,'figure2',...
    'Name'            ,'',...
    'PaperSize'       ,[20.98 29.68],...
    'PaperType'       ,'a4letter',...
    'Position'        , [left bottom widht height],...
    'Resize'          , 'off',...
    'Menu'            ,'none');
    
    
    
    
    set(figure2,'Name'            ,NameFig);   
%     if n==5
%         n=n+1;
%     end
    xc1=inter(n,1);
    yc1=inter(n,2);
    
    text0_10=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,12,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'center',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.3 0.89 0.2 0.1] ,...
        'String'                ,'Абсолютная основная погрешность',...
        'Visible'               ,'on');
    
    text0_11=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,12,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.3 0.85 0.2 0.1] ,...
        'String'                ,NameUnit,...
        'Visible'               ,'on');
    
    
    text0_20=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,12,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'center',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.5 0.89 0.2 0.1] ,...
        'String'                ,'Допустимая абсолютная основная погрешность',...
        'Visible'               ,'on');
    
    text0_21=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,12,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.5 0.85 0.2 0.1] ,...
        'String'                ,NameUnit,...
        'Visible'               ,'on');
    
    
    text0_30=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'Backgroundcolor'       ,[0.8 0.8 0.8],...
        'FontSize'              ,12,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'center',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.7 0.89 0.2 0.1] ,...
        'String'                ,'Примечание',...
        'Visible'               ,'on');
    
    
    
    
    
    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    CentrM1(1)=Centrs_metki(1,1,n);
    CentrM1(2)=Centrs_metki(1,2,n);
    EndS1(1)=CentrsEnd_strl(2,1,n);
    EndS1(2)=CentrsEnd_strl(2,2,n);
    
    axes1f2 = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes1f2,'Position',[0.01 0.74 0.3 0.18]);
    axes1f2;imshow(Images{1,n});hold on ;
    plot(xc1,yc1,'bx','LineWidth',2);
    plot(CentrM1(1),CentrM1(2),'rx','LineWidth',2);
    plot(EndS1(1),EndS1(2),'gx','LineWidth',2);
    
    
    
    text11=uicontrol(figure2,'Style','text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.3 0.74 0.2 0.1] ,...
        'String'                  , (sprintf('%2.1f',Otklonenie(n,1))),...
        'Visible'                 , 'on');
    
    
    text12=uicontrol(figure2,'Style','text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.5 0.74 0.2 0.1] ,...
        'String'                  , ['+/- ',(sprintf('%2.1f',dopusk(n,1)))],...
        'Visible'                 , 'on');
    
    
    text13=uicontrol(figure2,'Style','text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.7 0.75 0.2 0.1] ,...
        'Visible'                 , 'on');
    
    
    
    
    
    if ((abs(dopusk(n,1)))-(abs(Otklonenie(n,1))))>=0
        
        set(text11 ,'Foregroundcolor'   ,'b');
        set(text13 ,'String'            ,'Показания указателя в пределах допуска',...
            'Foregroundcolor'   ,'b');
        
        
    else
        set(text11 ,'Foregroundcolor'   , 'r');
        set(text13 ,'String'            , 'Указатель требует регулировки в этой точке',...
            'Foregroundcolor'  ,'r');
    end
    
    
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    CentrM2(1)=Centrs_metki(2,1,n);
    CentrM2(2)=Centrs_metki(2,2,n);
    EndS2(1)=CentrsEnd_strl(3,1,n);
    EndS2(2)=CentrsEnd_strl(3,2,n);
    
    axes2f2 = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes2f2,'Position',[0.01 0.55 0.3 0.18]);
    axes1f2;imshow(Images{2,n});hold on ;
    plot(xc1,yc1,'bx','LineWidth',2);
    plot(CentrM2(1),CentrM2(2),'rx','LineWidth',2);
    plot(EndS2(1),EndS2(2),'gx','LineWidth',2);
    
    
    
    
    text21=uicontrol(figure2,...
        'Style'                   ,'text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.3 0.55 0.2 0.1] ,...
        'String'                  , (sprintf('%2.1f',Otklonenie(n,2))),...
        'Visible'                 , 'on');
    
    
    text22=uicontrol(figure2,...
        'Style'                   ,'text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.5 0.55 0.2 0.1] ,...
        'String'                  ,['+/- ', (sprintf('%2.1f',dopusk(n,2)))],...
        'Visible'                 , 'on');
    
    
    text23=uicontrol(figure2,...
        'Style'                   ,'text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.7 0.55 0.2 0.1] ,...
        'Visible'                 , 'on');
    
    
    if ((abs(dopusk(n,2)))-(abs(Otklonenie(n,2))))>=0
        
        set(text21 ,'Foregroundcolor'   ,'b');
        set(text23 ,'String'            ,'Показания указателя в пределах допуска',...
            'Foregroundcolor'   ,'b');
        
        
    else
        set(text21 ,'Foregroundcolor'   , 'r');
        set(text23 ,'String'            , 'Указатель требует регулировки в этой точке',...
            'Foregroundcolor'  ,'r');
    end
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    CentrM3(1)=Centrs_metki(3,1,n);
    CentrM3(2)=Centrs_metki(3,2,n);
    EndS3(1)=CentrsEnd_strl(4,1,n);
    EndS3(2)=CentrsEnd_strl(4,2,n);
    
    
    
    axes3f2 = axes('Parent',figure2);
    set(gca, 'Visible','on');
    set(axes3f2,'Position',[0.01 0.36 0.3 0.18]);
    axes1f2;imshow(Images{3,n});hold on ;
    plot(xc1,yc1,'bx','LineWidth',2);
    plot(CentrM3(1),CentrM3(2),'rx','LineWidth',2);
    plot(EndS3(1),EndS3(2),'gx','LineWidth',2);
    
    
    text31=uicontrol(figure2,'Style','text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.3 0.36 0.2 0.1] ,...
        'String'                  , (sprintf('%2.1f',Otklonenie(n,3))),...
        'Visible'                 , 'on');
    
    text32=uicontrol(figure2,...
        'Style'                   ,'text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.5 0.36 0.2 0.1] ,...
        'String'                  , ['+/- ',(sprintf('%2.1f',dopusk(n,3)))],...
        'Visible'                 , 'on');
    
    
    text33=uicontrol(figure2,...
        'Style'                   ,'text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,12,...
        'FontWeight'              ,'normal',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.7 0.36 0.2 0.1] ,...
        'Visible'                 , 'on');
    
    
    
    if ((abs(dopusk(n,3)))-(abs(Otklonenie(n,3))))>=0
        
        set(text31 ,'Foregroundcolor'   ,'b');
        set(text33 ,'String'            ,'Показания указателя в пределах допуска',...
            'Foregroundcolor'   ,'b');
        
        
    else
        set(text31 ,'Foregroundcolor'   , 'r');
        set(text33 ,'String'            , 'Указатель требует регулировки в этой точке',...
            'Foregroundcolor'  ,'r');
    end
    
    if n~=1
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        CentrM4(1)=Centrs_metki(4,1,n);
        CentrM4(2)=Centrs_metki(4,2,n);
        EndS4(1)=CentrsEnd_strl(5,1,n);
        EndS4(2)=CentrsEnd_strl(5,2,n);
        
        
        
        axes4f2 = axes('Parent',figure2);
        set(gca, 'Visible','on');
        set(axes4f2,'Position',[0.01 0.17 0.3 0.18]);
        axes4f2;imshow(Images{4,n});hold on ;
        plot(xc1,yc1,'bx','LineWidth',2);
        plot(CentrM4(1),CentrM4(2),'rx','LineWidth',2);
        plot(EndS4(1),EndS4(2),'gx','LineWidth',2);
        
        
        text41=uicontrol(figure2,'Style','text', ...
            'Foregroundcolor'         ,'k',...
            'Backgroundcolor'         ,[0.8 0.8 0.8],...
            'FontSize'                ,12,...
            'FontWeight'              ,'normal',...
            'FontName'                ,'Arial',...
            'HorizontalAlignment'     ,'center',...
            'Units'                   ,'normalized', ...
            'Position'                , [0.3 0.17 0.2 0.1] ,...
            'String'                  , (sprintf('%2.1f',Otklonenie(n,4))),...
            'Visible'                 , 'on');
        
        text42=uicontrol(figure2,...
            'Style'                   ,'text', ...
            'Foregroundcolor'         ,'k',...
            'Backgroundcolor'         ,[0.8 0.8 0.8],...
            'FontSize'                ,12,...
            'FontWeight'              ,'normal',...
            'FontName'                ,'Arial',...
            'HorizontalAlignment'     ,'center',...
            'Units'                   ,'normalized', ...
            'Position'                , [0.5 0.17 0.2 0.1] ,...
            'String'                  , ['+/- ',(sprintf('%2.1f',dopusk(n,4)))],...
            'Visible'                 , 'on');
        
        
        text43=uicontrol(figure2,...
            'Style'                   ,'text', ...
            'Foregroundcolor'         ,'k',...
            'Backgroundcolor'         ,[0.8 0.8 0.8],...
            'FontSize'                ,12,...
            'FontWeight'              ,'normal',...
            'FontName'                ,'Arial',...
            'HorizontalAlignment'     ,'center',...
            'Units'                   ,'normalized', ...
            'Position'                , [0.7 0.17 0.2 0.1] ,...
            'Visible'                 , 'on');
        
        
        
        if ((abs(dopusk(n,4)))-(abs(Otklonenie(n,4))))>=0
            
            set(text41 ,'Foregroundcolor'   ,'b');
            set(text43 ,'String'            ,'Показания указателя в пределах допуска',...
                'Foregroundcolor'   ,'b');
            
            
        else
            set(text41 ,'Foregroundcolor'   , 'r');
            set(text43 ,'String'            , 'Указатель требует регулировки в этой точке',...
                'Foregroundcolor'  ,'r');
        end
    else
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    text5=uicontrol(figure2,'Style','text', ...
        'Foregroundcolor'         ,'k',...
        'Backgroundcolor'         ,[0.8 0.8 0.8],...
        'FontSize'                ,16,...
        'FontWeight'              ,'bold',...
        'FontName'                ,'Arial',...
        'HorizontalAlignment'     ,'center',...
        'Units'                   ,'normalized', ...
        'Position'                , [0.01 0.01 0.4 0.1] ,...
        'Visible'                 , 'on');
    
    %if n~=5
    if ((abs(dopusk(n,5)))-(abs(Otklonenie(n,5))))>=0
        
        set(text5 ,'String'            ,'Аварийный сигнализатор в норме',...
            'Foregroundcolor'   ,'b');
        
        
    else
        set(text5 ,'String'            ,'Аварийный сигнализатор не светится',...
            'Foregroundcolor'  ,'r');
    end
    %  else
    %      set(text5 ,'String'            ,' ');
    %  end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    text0_00=uicontrol(figure2,...
        'Style'                 ,'text', ...
        'Foregroundcolor'       ,'k',...
        'FontSize'              ,12,...
        'FontWeight'            ,'normal',...
        'FontName'              ,'Arial',...
        'HorizontalAlignment'   ,'center',...
        'Units'                 ,'normalized', ...
        'Position'              , [0.005 0.0  0.025 1] ,...
        'String'                ,'',...
        'Visible'               ,'on');
    
    
    if Goden(n)==0
        set(text0_00,'Backgroundcolor'      ,[0.8 1 0.3]);
    else
        set(text0_00,'Backgroundcolor'      ,[1 0 0]);
    end
end

%   EXIt2=uicontrol(figure2,...
%   'Style'               ,'pushbutton', ...
%   'Foregroundcolor'     ,'k',...
%   'Backgroundcolor'     ,[0.7 0.7 0.7],...
%   'FontSize'            ,12,...
%   'FontWeight'          ,'normal',...
%   'FontName'            ,'Arial',...
%   'Units'               ,'normalized', ...
%   'Position'            ,[0.85 0.04 0.1 0.04],...
%   'String'              ,'Закрыть окно',...
%   'callback'            ,['set(gcf,''userdata'',0)']);
%
%
% set(EXIt2,'KeyPressFcn',['set(gcf,''userdata'',0)']);
% uicontrol(EXIt2);
% waitfor(gcf,'userdata');
% delete (figure2);

