function  KD8071_4PM2_0000(varargin)
%головной модуль
global figure0 figure1  EXIt ...
       BEGin  NEXt PANel   PROv VISion VISion2...
       text1_1  text3 text4   ...
       left bottom widht height vid sobj...
       Ms X popinter PopCentrsEnd_strl...
       dopusk Shkala Datchik NameUnitDatcik   NumShkal...
       crop  threshold  thresholdX thresholdLed  thresholdOSV Open  Prov_1...
       

SCRsize=(get(0,'MonitorPositions'));
left=SCRsize(1);
bottom=SCRsize(2);
widht=SCRsize(3);
height=SCRsize(4)-19;

figure0 = figure...
  ('Color'           , [0.8 0.8 0.8],...
  'PaperPosition'   ,[0.25 2.5 8 6],...
  'NumberTitle'     ,'off', ...
  'Name'            ,'ЗАГРУЗКА',...
  'Tag'             ,'figure1',...
  'PaperSize'       ,[20.98 29.68],...
  'PaperType'       ,'a4letter',...
  'Position'        , [left bottom widht height],...
  'Resize'          , 'off',...
  'Menu'            ,'none',...
  'CloseRequestFcn' ,'');


text0=uicontrol(figure0,...
  'Style'           ,'text', ...
  'Foregroundcolor' ,'b',...
  'Backgroundcolor' ,[0.8 0.8 0.8],...
  'FontSize'        ,14,...
  'FontWeight'      ,'normal',...
  'FontName'        ,'Arial',...
  'HorizontalAlignment','left',...
  'Position'        ,[ 300  (bottom+height)-400 600 30],...
  'String'          ,'ЗАГРУЗКА',...
  'Visible'         ,'on');
       
  pause(0.1);     
 


try  
    
% %  % Загрузка CONSTANT  

 SOOB0=1;
load 'infodat8071_6(0000)';
% load 'Camera';

dopusk;
crop ;
threshold;
thresholdX;
thresholdLed;
Open;
PORTstr; 
Shkala;
NumShkal;
Datchik ;
NameUnitDatcik;
Ms;
Prov_1;
numserial;
thresholdOSV;
X;
popinter;
% Camera.BacklightCompensation='off';
% Camera.ExposureMode='manual';
% Camera.WhiteBalanceMode='manual';
% Camera.ExposureMode='manual';
% Camera.FrameRate=15000;
% Camera.Contrast=32;
% Camera.Brightness=50;
% Camera.WhiteBalance=5556;
% Camera.Saturation=32;
% Camera.Exposure=-3;
% Camera.Gain=0;
% Camera.Sharpness=46;
if numserial==0000
  
%     
   pause(0.1);     


   
    

SOOB0=2;

str=strcat('загрузка порта - ',' ',PORTstr);
set(text0,'String',str,...
  'Visible','on','Backgroundcolor',[0.8 0.8 0.8]); 

sobj = serial(PORTstr,'BaudRate',9600);
fopen(sobj);

% % fprintf(sobj,'@30');
% fprintf(sobj,'@50');

str=strcat('загрузка порта -',' ',PORTstr,' ','  выполнена' );
set(text0,...
    'String'           ,str,...
    'Visible'          ,'on',...
    'Backgroundcolor'  ,[0.8 0.8 0.8]); 

pause(1);
%  fprintf(sobj,'@50');

SOOB0=3;

%imaqreset;


set(text0,...
    'String'          ,'загрузка видеоустройства.',...
    'Visible'         ,'on',...
    'Backgroundcolor' ,[0.8 0.8 0.8]); 


vid= videoinput('winvideo', ID_camera, 'RGB24_640x480');

 %preview(vid); 

set(vid,...
    'FrameGrabInterval'        ,1,...
    'FramesPerTrigger'         ,160,...
    'Timeout'                  ,150,...
     'TriggerRepeat'           ,Inf);
triggerconfig(vid, 'Manual');
try
set(getselectedsource(vid),'BacklightCompensation',Camera.BacklightCompensation);
set(getselectedsource(vid),'WhiteBalanceMode',Camera.WhiteBalanceMode);
% set(getselectedsource(vid),'ExposureMode', Camera.ExposureMode);
set(getselectedsource(vid),'Contrast',     Camera.Contrast);
set(getselectedsource(vid),'Brightness',   Camera.Brightness);
set(getselectedsource(vid),'WhiteBalance', Camera.WhiteBalance);
set(getselectedsource(vid),'Exposure',     Camera.Exposure);
set(getselectedsource(vid),'Gain',         Camera.Gain);
set(getselectedsource(vid),'Saturation',   Camera.Saturation);
set(getselectedsource(vid),'Sharpness',    Camera.Sharpness);
pause(0.5);
catch
 err = lasterror;
        errordlg(err.message);    
end

start(vid);

pause(2);


SOOB0=4;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%           MASKS  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%





set(text0,'Visible','off'); 







str=datestr(now, 'dd.mm.yyyy'); 


figure1 = figure...
 ('Color'            , [0.8 0.8 0.8],...
  'PaperPosition'    ,[0.25 2.5 8 6],...
  'NumberTitle'      ,'off', ...
  'Name'             ,' Прибор КД8071-4 ***  РАБОЧЕЕ МЕСТО № 2 ***    ',...
  'Tag'              ,'figure1',...
  'PaperSize'        ,[20.98 29.68],...
  'PaperType'        ,'a4letter',...
  'Position'         , [left bottom widht height],...
  'Resize'           , 'off',...
  'Menu'             ,'none',...
  'CloseRequestFcn'  ,'Exit_my');


 delete(figure0);
%%%% часы%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
hp1 = uipanel('Parent',figure1,'FontSize',12,'Title','',...
    'BackgroundColor',[0.8 0.8 0.8],...
    'Position',[.03 .9 .15 .05]);


uicontrol('Parent',hp1 ,...
  'Style'           ,'text', ...
  'Foregroundcolor' ,'k',...
  'Backgroundcolor' ,[0.8 0.8 0.8],...
  'FontSize'        ,10,...
  'FontWeight'      ,'normal',...
   'units'           ,'normalized',...
  'FontName'        ,'Arial',...
  'Position'        ,[ 0.01 0.01 0.98 0.7 ],...
  'tag'             ,'table',...
   'String'          ,'',...
  'HorizontalAlignment','Center');
% set(findobj(gcf,'Tag','table'),'string',['Дата: ' str]);

 

set(findobj(gcf,'Tag','table'),'FontWeight','bold');
T = timer('Name','Timer_1','TimerFcn',{@timer_step},'Period',1,'ExecutionMode','fixedDelay'); 
tic 
start(T) 





% разделительная линия
uicontrol(figure1,...
  'Style'           ,'text', ...
  'Backgroundcolor' ,[0.4 0.4 0.6],...
  'units'           ,'normalized',...
  'Position'        ,[.32 0.05 0.002 0.9],...
  'HorizontalAlignment','left');
  
% Руководящая надпись 1
text1_1=uicontrol(figure1,...
  'Style'          ,'text', ...
  'Foregroundcolor','r',...
  'Backgroundcolor',[0.8 0.8 0.8],...
  'FontSize'       ,14,...
  'FontWeight'     ,'normal',...
  'FontName'       ,'Arial',...
  'Position'       ,[ 400 (bottom+height)-100 800 30],...
  'HorizontalAlignment','left',...
  'String'          ,'Подключите разъём, вставте прибор в гнездо и нажмите кнопку! ');


EXIt=uicontrol(figure1,'Style','pushbutton', ...
  'Foregroundcolor','k',...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'FontSize',12,...
  'FontWeight','normal',...
  'FontName','Arial',...
  'Position', [widht-250 bottom+50 200 30],...
  'String','ВЫХОД',...
  'callback','Exit_my');



% Кнопка "начать проверку прибора" 

BEGin=uicontrol(figure1,'Style','pushbutton', ...
  'Foregroundcolor','k',...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'FontSize',14,...
  'FontWeight','normal',...
  'FontName','Arial',...
  'Position',[ 450  (bottom+height)-190 500 50],...
  'String',' Автоматическая проверка ',...
  'Visible','off',...
  'callback','BEGin_Callback'); 
set(BEGin,'KeyPressFcn','BEGin_Callback' );

% Кнопка "проверки без камеры" 

VISion=uicontrol(figure1,'Style','pushbutton', ...
  'Foregroundcolor','k',...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'FontSize',14,...
  'FontWeight','normal',...
  'FontName','Arial',...
  'Position',[ 450  (bottom+height)-290 500 50],...
  'String',' Визуальная проверка 1',...
  'Visible','off',...
  'callback','VASion1_Callback'); 
set(VISion,'KeyPressFcn','VASion1_Callback' );

VISion2=uicontrol(figure1,'Style','pushbutton', ...
  'Foregroundcolor','k',...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'FontSize',14,...
  'FontWeight','normal',...
  'FontName','Arial',...
  'Position',[ 450  (bottom+height)-390 500 50],...
  'String',' Визуальная проверка 2',...
  'Visible','off',...
  'tag', 'VISion2',...
  'callback','VASion2_Callback'); 
set(VISion2,'KeyPressFcn','VASion2_Callback' );







% кнопка "следующий прибор"



NEXt=uicontrol(figure1,'Style','pushbutton', ...
  'Foregroundcolor','k',...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'FontSize',14,...
  'FontWeight','normal',...
  'FontName','Arial',...
  'Position',[ 450  (bottom+height)-290 500 50],...
  'String','СЛЕДУЮЩИЙ ПРИБОР ',...
  'Visible','off',...
  'callback','NEXt_Callback');

PROv=uicontrol(figure1,'Style','pushbutton', ...
  'Foregroundcolor','k',...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'FontSize',14,...
  'FontWeight','normal',...
  'FontName','Arial',...
  'Position',[ 450  (bottom+height)-290 500 50],...
  'String','ВЫБОРОЧНАЯ ПРОВЕРКА',...
  'Visible','off',...
  'callback','NEXt_Callback');





% Панель отображения хода проверки

PANel=uipanel(figure1,...
   'Foregroundcolor'       ,'k',...
  'Backgroundcolor'       ,[0.7 0.7 0.7],...
  'FontSize'              ,14,...
  'FontWeight'            ,'bold',...
  'FontName'              ,'Arial',...
  'Units'                 ,'normalized', ...
  'Position'              , [0.33 0.1 0.43 0.2] ,...  %'Position',[ 350+10  (bottom+height)-500 360 250],...
  'Visible'               ,'off');
  
text3=uicontrol('parent'  ,PANel,...
  'Style'                 ,'text', ...
  'Foregroundcolor'       ,'b',...
  'Backgroundcolor'       ,[0.7 0.7 0.7],...
  'FontSize'              ,12,...
  'FontWeight'            ,'normal',...
  'FontName'              ,'Arial' ,...
  'HorizontalAlignment'   ,'left',...
  'Units'                 ,'normalized', ...
  'Position'              , [0.01 0.32 0.98 0.45] ,...  %'Position',[ 350+45  (bottom+height)-400 300 30],...
  'String'                ,'',...
  'Visible'               ,'off');

text4=uicontrol(PANel,'Style','text', ...
  'Foregroundcolor',[0.7 1 0.5],...
  'Backgroundcolor',[0.7 0.7 0.7],...
  'Units'                 ,'normalized', ...
  'FontSize',14,...
  'FontWeight','bold',...
  'FontName','Arial',...
  'HorizontalAlignment','left',...
  'Position',[0.01 0.05 0.98 0.3],...
  'String','',...
  'Visible','off');

% Panel_Video= uipanel('Parent',figure1,'FontSize',12,'Title','',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'Position',[0.01 0.6 0.3 0.3],'Visible','off');
% 
% VIDeo=uicontrol(figure1,'Style','pushbutton', ...
%   'Foregroundcolor','k',...
%   'Backgroundcolor',[0.7 0.7 0.7],...
%   'FontSize',12,...
%   'FontWeight','normal',...
%   'FontName','Arial',...
%   'Position', [widht-250 bottom+150 200 30],...
%   'String','ВИДЕО',...
%   'callback',@vidpreview);


set(BEGin,'KeyPressFcn','BEGin_Callback' );
pause(1)
set(VISion,'Visible','on' );
set(BEGin,'Visible','on' );
set(findobj('tag', 'VISion2'),'Visible','off');
uicontrol(BEGin);

else
 set(text0,...
      'String'           ,'подключите блок № 0000 ',...
      'Foregroundcolor'  ,'b',...   
       'Visible'         ,'on',...
       'Backgroundcolor' ,[0.8 0.8 0.8]); 

uicontrol(figure0,'Style','pushbutton','FontName','Arial','String','Ok',...
     'Position',[ 450  (bottom+height)-500 100 50],'FontSize',14,...
     'FontWeight','normal', 'Tag','Yes_button',...
     'callback' ,'set(gcf,''userdata'',0)');
 waitfor(gcf,'userdata')
       
      delete(figure0);
end

catch
 switch SOOB0;
     
      case 1  
     set(text0,...
      'String'           ,'Ошибка в загрузке из файла infodat8071_5',...
      'Foregroundcolor'  ,'b',...   
       'Visible'         ,'on',...
       'Backgroundcolor' ,[0.8 0.8 0.8]); 

uicontrol(figure0,'Style','pushbutton','FontName','Arial','String','Ok',...
     'Position',[ 450  (bottom+height)-500 100 50],'FontSize',14,...
     'FontWeight','normal', 'Tag','Yes_button',...
     'callback' ,'set(gcf,''userdata'',0)');
 waitfor(gcf,'userdata')
 
 delete(figure0);
     
          
    case 2 
        
      str=strcat('Ошибка в открытии порта  - ',' ',PORTstr);  
      set(text0,...
       'String'           ,str,...
       'Foregroundcolor'  ,'b',...   
       'Visible'          ,'on',...
       'Backgroundcolor'  ,[0.8 0.8 0.8]); 

Yes_button=uicontrol...
    (figure0,...
    'Style'              ,'pushbutton',...
    'FontName'           ,'Arial',...
    'String'             ,'Ok',...
    'Position'           ,[ 450  (bottom+height)-500 100 50],...
    'FontSize'           ,14,...
    'FontWeight'         ,'normal',...
    'Tag'                ,'Yes_button',...
    'callback'           ,['set(gcf,''userdata'',0)']);

 waitfor(gcf,'userdata')
 
delete(figure0);
      
    case 3
      set(text0,'String','Ошибка в открытии видеоустройства.',...
       'Foregroundcolor','r',...   
  'Visible','on','Backgroundcolor',[0.8 0.8 0.8]); 

Yes_button=uicontrol(figure0,'Style','pushbutton','FontName','Arial','String','Ok',...
     'Position',[ 450  (bottom+height)-500 100 50],'FontSize',14,...
     'FontWeight','normal', 'Tag','Yes_button',...
     'callback' ,['set(gcf,''userdata'',0)']);
 waitfor(gcf,'userdata')


%       fprintf(sobj,'@20');
%       fprintf(sobj,'@40');
%       fprintf(sobj,'@60');
      fclose(sobj) % disconnecting the instrument

      clear sob
      
  
  
      
      delete(figure0);
      
      clear all
      
     case 4
      set(text0,'String','Ошибка в загрузке из файлов масок',...
       'Foregroundcolor','r',...   
  'Visible','on','Backgroundcolor',[0.8 0.8 0.8]); 

Yes_button=uicontrol(figure1,'Style','pushbutton','FontName','Arial','String','Ok',...
     'Position',[ 450  (bottom+height)-500 100 50],'FontSize',14,...
     'FontWeight','normal', 'Tag','Yes_button',...
     'callback' ,'set(gcf,''userdata'',0)');
 waitfor(gcf,'userdata')

     
%       fprintf(sobj,'@20');
%       fprintf(sobj,'@40');
%       fprintf(sobj,'@60');
      fclose(sobj) % disconnecting the instrument
      %closepreview(vid);
      clear vid
      clear sob
      
      delete(figure0);
      
      clear all
%       
%  
%       
%       
 end

end

% uicontrol(BEGin); 

% function vidpreview(source,eventdata)
% global vid left bottom widht height VIDeo figure000 Panel_Video
% 
% % figure000 = figure...
% %   ('Color'           , [0.8 0.8 0.8],...
% %   'NumberTitle'     ,'off', ...
% %   'Name'            ,'Видео',...
% %   'Tag'             ,'figure_vid',...
% %   'PaperSize'       ,[20.98 29.68],...
% %   'PaperType'       ,'a4letter',...
% %   'Position'        , [20 height-150-height/4 widht/3.8 (widht/3.8)*3/4],...
% %   'Resize'          , 'on',...
% %   'CloseRequestFcn'  ,@closeprev_vid,...
% %   'Menu'            ,'none');
% 
% % uicontrol('String', 'Выход', 'Callback', 'close(gcf)');  
% 
% vidRes = get(vid, 'VideoResolution'); 
% nBands = get(vid, 'NumberOfBands'); 
% hImage = image( zeros(vidRes(2), vidRes(1), nBands) ); 
% A=get(Panel_Video,'Position');
% set(gca,'Position',[A(1)+0.005 A(2)+0.005 A(3)-0.01 A(4)-0.01]);
% preview(vid, hImage); 
% set(Panel_Video,'Visible'               ,'on');
% 
% set(VIDeo,'Visible'               ,'off');
% 
% function closeprev_vid(source,eventdata)
% 
% global vid left bottom widht height VIDeo
% 
% delete(findobj('Tag'             ,'figure_vid')); 
% set(VIDeo,'Visible'               ,'on');
% % 
% % 
function timer_step(varargin) 
set(findobj(gcf,'Tag','table'),'String',datestr(now,0)) 
% % 
