function Light(varargin)
global vid Camera CROP S Lim

% load 'infodat8110_00';

SCRsize=(get(0,'MonitorPositions'));
widht=SCRsize(3);
height=SCRsize(4)-19;


figure0000 = figure...
    ('Color'           , [0.925 0.914 0.844],...
    'PaperPosition'   ,[0.25 2.5 8 6],...
    'NumberTitle'     ,'off', ...
    'Name'            ,'KD8071',...
    'Tag'             ,'figure0',...
    'PaperSize'       ,[20.98 29.68],...
    'PaperType'       ,'a4letter',...
    'Position'        , [widht/4  height/4 widht/1.5 height/1.5],...%     'Position'        , [0.45 0.64 0.5 0.285],...
    'Resize'          , 'off',...
    'Menu'            ,'none',...
    'CloseRequestFcn' ,@myclosereq20);

hp1 = uipanel('Parent',figure0000,...
    'Title'           ,'',...
    'FontName'        ,'Arial',...
    'FontSize'        ,8,...
    'Units'           ,'normalized',...
    'Position'        ,[0.03 0.1 0.94 0.88]);

%  load 'infolight_8071_002';








Camera.BacklightCompensation='off';
% Camera.ExposureMode='manual';
Camera.WhiteBalanceMode='manual';
% Camera.ExposureMode='manual';
% Camera.FrameRate=15000;
Camera.Contrast=35;
Camera.Brightness=45;
Camera.WhiteBalance=5556;
Camera.Saturation=32;
Camera.Exposure=-7;
Camera.Gain=0;
Camera.Sharpness=46;
CROP(1,:)=[290.5100  301.5100  113.9800   61.9800];
S(1)=113.9800*61.9800;

Lim(1,:)=[0.015, 0.04];
 Lim(2,:)=[ 0.2,0.3];  
CROP(2,:)=[63.5100  394.5100   64.9800   62.9800];
S(2)=64.9800*   62.9800;
vid= videoinput('winvideo', 2, 'RGB24_640x480');

 %preview(vid); 

set(vid,...
    'FrameGrabInterval'        ,1,...
    'FramesPerTrigger'         ,160,...
    'Timeout'                  ,150,...
     'TriggerRepeat'           ,Inf);
triggerconfig(vid, 'Manual');
try
set(getselectedsource(vid),'BacklightCompensation',Camera.BacklightCompensation);
% set(getselectedsource(vid),'ExposureMode', Camera.ExposureMode);
set(getselectedsource(vid),'WhiteBalanceMode',Camera.WhiteBalanceMode);
set(getselectedsource(vid),'Contrast',     Camera.Contrast);
set(getselectedsource(vid),'Brightness',   Camera.Brightness);
set(getselectedsource(vid),'WhiteBalance', Camera.WhiteBalance);
set(getselectedsource(vid),'Exposure',     Camera.Exposure);
set(getselectedsource(vid),'Gain',         Camera.Gain);
set(getselectedsource(vid),'Saturation',   Camera.Saturation);
set(getselectedsource(vid),'Sharpness',    Camera.Sharpness);

pause(0.5);
catch
 err = lasterror;
        warndlg(err.message);    
end

start(vid);

pause(2);

Panel_Video= uipanel('Parent',hp1,'FontSize',12,'Title','',...
    'BackgroundColor',[0.8 0.8 0.8],...
    'Position',[0.01 0.02 0.8 0.96],'Visible','on');
axses1=axes('Parent',Panel_Video','Position',[0.02 0.09 0.96 0.8218 ],'Box','off','TickLength',[0 0],'Visible','on');
vidRes = get(vid, 'VideoResolution');
nBands = get(vid, 'NumberOfBands');
% nBands=3;
% % hImage = image( zeros(VerticalStol, HorizontalStol,3),'parent',findobj('tag', 'axes1_hsp1_3'),'HitTest','off' );
hImage = image( zeros(vidRes(2), vidRes(1), nBands));
preview(vid, hImage);

hp2 = uipanel('Parent',figure0000,...
    'Title'           ,'',...
    'FontName'        ,'Arial',...
    'FontSize'        ,8,...
    'Units'           ,'normalized',...
    'Position'        ,[0.03 0.02 0.77 0.08]);
uicontrol('Parent'    ,hp2,...
    'style'           ,'text',...
    'units'           ,'normalized', ...
    'position'        ,[0.05 0.05 0.25 0.9 ],...
    'fontsize'        ,10,...
    'Backgroundcolor' ,[0.925 0.914 0.844],...
    'String'          ,'Интенсивность 1');
uicontrol('Parent'    ,hp2,...
    'style'           ,'text',...
    'units'           ,'normalized', ...
    'position'        ,[0.25 0.05 0.25 0.9 ],...
    'fontsize'        ,10,...
    'tag'             ,'Intens1',...
    'Backgroundcolor' ,[0.925 0.914 0.844],...
    'String'          ,'');
uicontrol('Parent'    ,hp2,...
    'style'           ,'text',...
    'units'           ,'normalized', ...
    'position'        ,[0.75 0.05 0.25 0.9 ],...
    'fontsize'        ,10,...
    'tag'             ,'Intens2',...
    'Backgroundcolor' ,[0.925 0.914 0.844],...
    'String'          ,'');uicontrol('Parent'    ,hp2,...
    'style'           ,'text',...
    'units'           ,'normalized', ...
    'position'        ,[0.5 0.05 0.25 0.9 ],...
    'fontsize'        ,10,...
    'Backgroundcolor' ,[0.925 0.914 0.844],...
    'String'          ,'Интенсивность 2');




hp3 = uipanel('Parent',figure0000,...
    'Title'           ,'',...
    'FontName'        ,'Arial',...
    'FontSize'        ,8,...
    'Units'           ,'normalized',...
    'Position'        ,[0.8 0.02 0.17 0.08]);
G_Light=uicontrol('Parent'    ,hp3,...
    'style'           ,'pushbutton',...
    'units'           ,'normalized', ...
    'position'        ,[0.1 0.1 0.8 0.8 ],...
    'foregroundcolor'  ,[0 0 0],...
    'fontsize'        ,10,...
    'Callback'        , @getLight,...
    'String'          ,'Измерить');


function getLight(source,eventdata)
    INT(1)=0; INT(2)=0;
 for n=1:5;
     
      A=getsnapshot(vid);
      for m=1:2
      AA1=imcrop(A,CROP(m,:));
      
      RGB=im2double(AA1);
            %разделение цветов
            r=RGB(:,:,1);
            g=RGB(:,:,2);
            b=RGB(:,:,3);
            I=(r+g+b)/3;
            intens(m)=sum(sum(I))/S(m);
            
      end
      INT(1)=INT(1)+intens(1);
      INT(2)=INT(2)+intens(2);
 end
 intens(1)=INT(1)/5;
 intens(2)=INT(2)/5;
    if intens(1)>Lim(1,1)&&intens(1)<Lim(1,2)
         
    set(findobj('tag','Intens1'),'string',num2str(intens(1)),'Foregroundcolor' ,[0 0 0]);
    elseif intens(1)>=Lim(1,2)
    set(findobj('tag','Intens1'),'string',['+  ',num2str(intens(1))],'Foregroundcolor' ,[1 0 0]);
    elseif intens(1)<=Lim(1,1)
    set(findobj('tag','Intens1'),'string',['-  ',num2str(intens(1))],'Foregroundcolor' ,[1 0 0]);
     end
     
    if intens(2)>Lim(2,1)&&intens(2)<Lim(2,2)
    set(findobj('tag','Intens2'),'string',num2str(intens(2)),'Foregroundcolor' ,[0 0 0]);
    elseif intens(2)>=Lim(2,2)
    set(findobj('tag','Intens2'),'string',['+   ',num2str(intens(2))],'Foregroundcolor' ,[1 0 0]);
    elseif intens(2)<=Lim(2,1) 
    set(findobj('tag','Intens2'),'string',['-   ',num2str(intens(2))],'Foregroundcolor' ,[1 0 0]);
     end
        
    end



function myclosereq20(source,eventdata)
        
% stop(vid);
 delete(vid)
     %
     clear vid
    
     
        closereq;
    end

end


